# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/cryptmain";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."cryptmain".device = "/dev/disk/by-partlabel/main";
  boot.initrd.luks.devices."cryptswap".device = "/dev/disk/by-partlabel/swap";

  fileSystems."/boot" =
    { device = "/dev/disk/by-partlabel/ESP";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/mapper/cryptswap"; }
    ];

  nix.maxJobs = lib.mkDefault 8;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
